### ISSUE TITLE
Problem in showing photos in the slider on the home page by IE8

### ISSUE THREAD

**Issue by alvinkywong** [kossa/taikoo#4]
When the homepage is viewing by IE8, only the first photo is being shown in each slot. The problem does not happen on Chrome.

**Comment by kossa** [comment]
To make the image full responsive and full width I used "cover" propriety of CSS3, is not supported for IE8 http://caniuse.com/#feat=background-img-opts

**Comment by alvinkywong** [comment]
Does it mean that nothing we can do to let IE8 users to view the video and photos on the slider?

**Comment by kossa** [comment]
The second problem is the video will not play on IE8, because IE8 cannot read video directly in the browser : http://caniuse.com/#search=video
