### ISSUE TITLE
indicator of slider is overlapping with super in animation

### ISSUE THREAD

**Issue by alvinkywong** [kossa/taikoo#8]
May I know how can we disable the indicator on the bottom of the slider? those dots are now overlapping with the super of the animation. see attached figure. 

![screen capture](https://cloud.githubusercontent.com/assets/12066677/7452750/3c34845c-f294-11e4-8901-8d69b952cea6.jpg)

**Comment by kossa** [comment]
Go to https://github.com/kossa/taikoo/blob/master/css/style.css#L223
at the end add : `  display: none!important;`
